### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by Sayonnara** [Rafahmachado/Cardapio-Digital-Home-Food#3]
Oi! Está com infertace ou não ?

Vai acrescentar acessibilidade ?

**Comment by Rafahmachado** [comment]
Oi ,vc diz interface?
Precisamos incluir interface ,e acessibilidade ainda não pensei como inserir ainda

**Comment by Sayonnara** [comment]
Ah ! sim entendi, está no projeto futuro, Legal

**Comment by Rafahmachado** [comment]
> Ah! sim entendi, está no projeto futuro, Legal

Isso mesmo!
